
coverage:
	@printf "Running coverage unittesting and writting results to a html file..."
	coverage run -m unittest discover
	coverage html
	@printf "To open it run:"
	@printf "Mac -- open -a Google\ Chrome htmlcov/index.html"
	@printf "Linux -- firefox htmlcov/index.html"
