
coverage:
	@printf "Running coverage unittesting and writting results to a html file...\n"
	coverage run -m unittest discover
	coverage html
	@printf "To open it run:\n"
	@printf "Mac -- open -a Google\ Chrome htmlcov/index.html\n"
	@printf "Linux -- firefox htmlcov/index.html\n"
